backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: ../../assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Posttype", name: "posttype", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "service"
    label: "Service"
    folder: "content/home/services"
    create: true
    fields:
      - { label: "Posttype", name: "posttype", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Image", name: "image", widget: image }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }