backend:
  name: gatsby-omniwyse
  branch: master


media_folder: static/assets
public_folder: assets

collections:
  - name: Services
    label: Services
    create: true
    folder: "content/home/services"
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
      - { name: posttype, label: Posttype }
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: posttype, label: Posttype }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  