backend:
  name: test-repo
  repo: Lintachaudhari/gatsby-omniwyse

media_folder: static/assets
public_folder: assets

collections:
  - name: About
    label: about
    create: true
    folder: "content/about"
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
      # - { label: "Image", name: "image", widget: "image" }