backend:
  name: test-repo
  repo: Lintachaudhari/gatsby-omniwyse

media_folder: static/assets
public_folder: assets

collections:
  - name: Services
    label: Services
    create: true
    folder: "content/home/services"
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
      - { name: posttype, label: Posttype }
      # - { label: "Image", name: "image", widget: "image" }
  