backend:
  name: git-gateway
  branch: master
  repo: Lintachaudhari/gatsby-omniwyse

media_folder: static/assets
public_folder: assets

collections:
  - name: Services
    label: Services
    create: true
    folder: "content/home/services"
    fields:
      - { name: "posttype", label: "Posttype", widget: "string" }
      - { name: "path", label: "Path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { name: "date", label: "Date", widget: "date" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: "posttype", label: "Posttype", widget: "string" }
      - { name: "date", label: Date, widget: date }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
  

